# -----------------------------------------------------
# HYPRLAND COLOR PALETTE (Gruvbox Dark)
# Author: AMOS-fet
# -----------------------------------------------------

# --- BACKGROUND & FOREGROUND ---
$bg             = rgb(282828)
$bg_bright      = rgb(504945)
$fg             = rgb(F9EDD2)
$fg_dim         = rgb(D3C29F)

# --- NORMAL COLORS (Darker/Standard) ---
$red            = rgb(CA2420)
$green          = rgb(98971C)
$yellow         = rgb(D89822)
$blue           = rgb(448385)
$purple         = rgb(83A497)
$aqua           = rgb(679B69)
$orange         = rgb(D75C0F)

# --- BRIGHT COLORS (Lighter/Vibrant) ---
$red_br         = rgb(F94835)
$green_br       = rgb(B7B827)
$yellow_br      = rgb(F9BB31)
$blue_br        = rgb(83A497)
$purple_br      = rgb(D184CC)
$aqua_br        = rgb(8EBE7A)
$orange_br      = rgb(FE7C0D)

# --- HYPRLAND BORDER CONFIGURATION ---
$active_border      = $orange_br $orange 45deg
$inactive_border    = $bg_bright
