# -----------------------------------------------------
# BTOP COLOR PALETTE (Gruvbox Material Custom)
# Author: AMOS-fet
# -----------------------------------------------------

# -----------------------------------------------------
# 1. Interface
# -----------------------------------------------------
theme[main_bg]="#282828"     
theme[main_fg]="#F9EDD2"     
theme[title]="#F9EDD2"       
theme[hi_fg]="#F94835"       
theme[selected_bg]="#FE7C0D" 
theme[selected_fg]="#282828" 
theme[inactive_fg]="#A89985" 
theme[graph_text]="#F9EDD2"  

# -----------------------------------------------------
# 2. Borders
# -----------------------------------------------------
theme[proc_misc]="#F9EDD2"  
theme[cpu_box]="#F9EDD2"    
theme[mem_box]="#F9EDD2"    
theme[net_box]="#F9EDD2"    
theme[proc_box]="#F9EDD2"   
theme[div_line]="#A89985"   

# -----------------------------------------------------
# 3. Gradients
# -----------------------------------------------------
# temp
theme[temp_start]="#B7B827" 
theme[temp_mid]="#F9BB31"   
theme[temp_end]="#F94835"   

# cpu
theme[cpu_start]="#B7B827"
theme[cpu_mid]="#F9BB31"
theme[cpu_end]="#F94835"

# memory
theme[free_start]="#B7B827"
theme[free_mid]="#F9BB31"
theme[free_end]="#F94835"

# cache
theme[cached_start]="#8EBE7A"
theme[cached_mid]="#8EBE7A"
theme[cached_end]="#8EBE7A"

# available
theme[available_start]="#F9BB31"
theme[available_mid]="#F9BB31"
theme[available_end]="#F9BB31"

# used
theme[used_start]="#F94835"
theme[used_mid]="#F94835"
theme[used_end]="#F94835"

# download
theme[download_start]="#83A497"
theme[download_mid]="#83A497"
theme[download_end]="#83A497"

# upload
theme[upload_start]="#D184CC"
theme[upload_mid]="#D184CC"
theme[upload_end]="#D184CC"
