# -----------------------------------------------------
# GLOBAL COLOR PALETTE (Gruvbox Material Custom)
# Author: AMOS-fet
# -----------------------------------------------------

# Black
black=#282828
black_hd=#1B1E1F
black_sf=#504945

# Red
red=#CA2420
red_br=#F94835

# Green
green=#98971C
green_br=#B7B827

# Yellow
yellow=#D89822
yellow_br=#F9BB31

# Blue
blue=#448385
blue_br=#83A497

# Purple
purple=#A962AF
purple_br=#D184CC

# Aqua
aqua=#679B69
aqua_br=#8EBE7A

# White
white=#F9EDD2
white_hd=#FCF3DB
white_sf=#D3C29F

# Gray
gray=#8F8173
gray_br=#A89985

# Orange
orange=#D75C0F
orange_br=#FE7C0D
