#!/bin/bash

# -----------------------------------------------------
# File: theme-switch.sh
# Description: Switches system-wide theme (Dark/Light)
#              Manages symlinks, GTK, Browsers, and reload triggers.
# Author: AMOS-fet
# -----------------------------------------------------

# -----------------------------------------------------
# 1. Variables & Arguments
# -----------------------------------------------------

MODE=$1
DOTFILES="$HOME/dotfiles"
CONFIG_DIR="$HOME/.config"

# Validate input
if [[ "$MODE" != "dark" && "$MODE" != "light" ]]; then
    echo " Error: Specify mode [dark|light]"
    exit 1
fi

echo " Switching to $MODE theme..."

if [ "$MODE" == "dark" ]; then
    # Dark Mode Settings
    GTK_THEME="Colloid-Orange-Dark-Gruvbox"
    CURSOR_THEME="phinger-cursors-light" # Light cursor for contrast
    COLOR_SCHEME="prefer-dark"
    MICRO_COLOR="gruvbox-dark"
    VIM_BG="dark"
    FIREFOX_OVERRIDE=0 # 0=Dark
else
    # Light Mode Settings
    GTK_THEME="Colloid-Orange-Light-Gruvbox"
    CURSOR_THEME="phinger-cursors-dark" # Dark cursor for contrast
    COLOR_SCHEME="prefer-light"
    MICRO_COLOR="gruvbox-light"
    VIM_BG="light"
    FIREFOX_OVERRIDE=1 # 1=Light
fi

# -----------------------------------------------------
# 2. Symlink Management
# -----------------------------------------------------

# --- Hyprland ---
ln -sf "$DOTFILES/hypr/.config/hypr/colors-$MODE.conf" "$CONFIG_DIR/hypr/colors.conf"

# --- Waybar ---
ln -sf "$DOTFILES/waybar/.config/waybar/colors-$MODE.css" "$CONFIG_DIR/waybar/colors.css"

# --- Kitty Terminal ---
ln -sf "$DOTFILES/kitty/.config/kitty/theme-$MODE.conf" "$CONFIG_DIR/kitty/theme.conf"

# --- Rofi Launcher ---
ln -sf "$DOTFILES/rofi/.config/rofi/config-$MODE.rasi" "$CONFIG_DIR/rofi/config.rasi"

# --- Starship Prompt ---
ln -sf "$DOTFILES/starship/.config/starship-$MODE.toml" "$CONFIG_DIR/starship.toml"

# --- Mako Notifications ---
ln -sf "$DOTFILES/mako/.config/mako/$MODE" "$CONFIG_DIR/mako/config"

# --- Yazi File Manager ---
ln -sf "$DOTFILES/yazi/.config/yazi/theme-$MODE.toml" "$CONFIG_DIR/yazi/theme.toml"

# --- Pacseek ---
PACSEEK_DIR="$CONFIG_DIR/pacseek"
mkdir -p "$PACSEEK_DIR"
ln -sf "$DOTFILES/pacseek/.config/pacseek/config-$MODE.json" "$PACSEEK_DIR/config.json"

# -----------------------------------------------------
# 3. Application Specific Configs
# -----------------------------------------------------

# --- Wallpaper (SWWW) ---
# Executes the separate script to apply wallpaper and swww settings
$DOTFILES/scripts/apply-neon-$MODE.sh &

# --- Micro Editor ---
MICRO_SETTINGS="$CONFIG_DIR/micro/settings.json"
if [ -f "$MICRO_SETTINGS" ]; then
    sed -i "s/\"colorscheme\": \".*\"/\"colorscheme\": \"$MICRO_COLOR\"/" "$MICRO_SETTINGS"
    echo "Micro theme set to: $MICRO_COLOR"
else
    echo " Warning: Micro settings.json not found."
fi

# --- Neovim (LazyVim) ---
NVIM_CONFIG_DIR="$DOTFILES/nvim/lua/config"
mkdir -p "$NVIM_CONFIG_DIR"
echo "vim.o.background = \"$VIM_BG\"" > "$NVIM_CONFIG_DIR/bg_mode.lua"

# --- LibreWolf / Firefox ---
FIREFOX_PROFILE=$(find "$HOME/.librewolf" -maxdepth 2 -type d -name "*.default-default" 2>/dev/null | head -n 1)
# Fallback to .default if .default-default not found
if [ -z "$FIREFOX_PROFILE" ]; then
    FIREFOX_PROFILE=$(find "$HOME/.librewolf" -maxdepth 2 -type d -name "*.default" 2>/dev/null | head -n 1)
fi

if [ -n "$FIREFOX_PROFILE" ]; then
    CHROME_DIR="$FIREFOX_PROFILE/chrome"
    mkdir -p "$CHROME_DIR"

    ln -sf "$DOTFILES/librewolf/chrome/userChrome-$MODE.css" "$CHROME_DIR/userChrome.css"
    ln -sf "$DOTFILES/librewolf/chrome/userContent-$MODE.css" "$CHROME_DIR/userContent.css"

    USER_JS="$FIREFOX_PROFILE/user.js"
    echo "user_pref(\"layout.css.prefers-color-scheme.content-override\", $FIREFOX_OVERRIDE);" > "$USER_JS"
    
    if [ "$MODE" == "dark" ]; then
         echo 'user_pref("ui.systemUsesDarkTheme", 1);' >> "$USER_JS"
    else
         echo 'user_pref("ui.systemUsesDarkTheme", 0);' >> "$USER_JS"
    fi
    
    echo " Updated LibreWolf theme in: $(basename "$FIREFOX_PROFILE")"
else
    echo " Warning: LibreWolf profile not found."
fi

# --- Neovim/Lazyvim ---
NVIM_BG_FILE="$CONFIG_DIR/nvim/lua/config/bg_mode.lua"

echo "-- Auto-generated by theme-switch.sh" > "$NVIM_BG_FILE"
echo "vim.o.background = \"$MODE\"" >> "$NVIM_BG_FILE"

echo "Neovim background set to: $MODE"

# --- Spicetify/Spotify ---
if pgrep -x "spotify" > /dev/null; then
    SPOTIFY_RUNNING=1
else
    SPOTIFY_RUNNING=0
fi

# -----------------------------------------------------
# 4. GTK & UI Appearance
# -----------------------------------------------------

THEMES_SOURCE="$DOTFILES/themes/.themes"
GTK_OVERRIDE_SOURCE="$DOTFILES/themes/.themes/gtk" 

echo " Setting GTK Theme: $GTK_THEME"

rm "$CONFIG_DIR/gtk-4.0/assets" 2>/dev/null
ln -sf "$THEMES_SOURCE/$GTK_THEME/gtk-4.0/assets" "$CONFIG_DIR/gtk-4.0/assets"

ln -sf "$GTK_OVERRIDE_SOURCE/$MODE.css" "$CONFIG_DIR/gtk-4.0/gtk.css"
ln -sf "$GTK_OVERRIDE_SOURCE/$MODE.css" "$CONFIG_DIR/gtk-3.0/gtk.css"

# GSettings (Gnome Interface)
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
gsettings set org.gnome.desktop.interface color-scheme "$COLOR_SCHEME"
gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME"

# Update settings.ini files
GTK3_SETTINGS="$CONFIG_DIR/gtk-3.0/settings.ini"
GTK4_SETTINGS="$CONFIG_DIR/gtk-4.0/settings.ini"

if [ -f "$GTK3_SETTINGS" ]; then
    sed -i "s/^gtk-theme-name=.*/gtk-theme-name=$GTK_THEME/" "$GTK3_SETTINGS"
fi
if [ -f "$GTK4_SETTINGS" ]; then
    sed -i "s/^gtk-theme-name=.*/gtk-theme-name=$GTK_THEME/" "$GTK4_SETTINGS"
fi

# Hyprland Cursor (Immediate effect)
hyprctl setcursor "$CURSOR_THEME" 24

# -----------------------------------------------------
# 5. Reload System Services
# -----------------------------------------------------

# Reload Waybar
pkill waybar && hyprctl dispatch exec waybar

# Reload Kitty (instances)
killall -SIGUSR1 kitty 2>/dev/null

# Reload Mako
makoctl reload

# Reload Hyprland
hyprctl reload 1> /dev/null

# Reload Spicetify
spicetify config current_theme custom color_scheme Gruvbox-$MODE 1> /dev/null
spicetify apply 1> /dev/null

if [ "$SPOTIFY_RUNNING" -eq 0 ]; then
    sleep 0.5
    pkill -x spotify
fi

# Notify User
notify-send "Theme Changed" "Applied $MODE theme successfully"

echo " Done!"
