# --- GRUVBOX LIGHT MASTER ---

# Base
background  #fbf1c7
foreground  #3c3836

# Black
# color0 (Normal) = Dim Background (Cream Darker)
color0  #f2e5bc
# color8 (Bright) = Gray (Comments)
color8  #928374

# Red
color1  #cc241d
# Bright Red (Darker/Blood)
color9  #9d0006

# Green
color2  #98971a
# Bright Green (Darker)
color10 #79740e

# Yellow
color3  #d79921
# Bright Yellow (Darker)
color11 #b57614

# Blue
color4  #458588
# Bright Blue (Darker)
color12 #076678

# Purple
color5  #b16286
# Bright Purple (Darker)
color13 #8f3f71

# Aqua
color6  #689d6a
# Bright Aqua (Darker)
color14 #427b58

# White
# color7 (Normal) = Dim FG (Grayish text)
color7  #7c6f64
# color15 (Bright) = Main FG (Darkest text)
color15 #3c3836

# Orange
color16 #d65d0e
# Bright Orange (Darker)
color17 #af3a03

# --- UI COLORS ---

url_color #076678

# Selection: Bright Orange Background with Cream Text
selection_background  #af3a03
selection_foreground  #fbf1c7

# Cursor: Dark Block with Cream Text
cursor                #3c3836
cursor_text_color     #fbf1c7

# --- TABS (Powerline Style) ---
tab_bar_style powerline

# Active Tab: Bright Orange BG, Cream Text
active_tab_background   #af3a03
active_tab_foreground   #fbf1c7
active_tab_font_style   bold

# Inactive Tab: Normal Orange BG, Cream Text
inactive_tab_background #d65d0e
inactive_tab_foreground #fbf1c7
inactive_tab_font_style normal

text_composition_strategy 1.0 40
