# -----------------------------------------------------
# KITTY COLOR PALETTE (Gruvbox Material Custom)
# Author: AMOS-fet
# -----------------------------------------------------


# Base
background  #282828
foreground  #F9EDD2

# Black
# color0 (Normal) = Background (Dark)
color0  #282828
# color8 (Bright) = Gray (Comments)
color8  #8F8173

# Red
color1  #CA2420
# Bright Red (Pastel/Lighter)
color9  #F94835

# Green
color2  #98971C
# Bright Green (Pastel/Lighter)
color10 #B7B827

# Yellow
color3  #D89822
# Bright Yellow (Pastel/Lighter)
color11 #F9BB31

# Blue
color4  #448385
# Bright Blue (Pastel/Lighter)
color12 #83A497

# Purple
color5  #A962AF
# Bright Purple (Pastel/Lighter)
color13 #D184CC

# Aqua
color6  #679B69
# Bright Aqua (Pastel/Lighter)
color14 #8EBE7A

# White
# color7 (Normal) = FG Dim (Grayish)
color7  #D3C29F
# color15 (Bright) = FG Normal (Cream)
color15 #F9EDD2

# Orange
color16 #D75C0F
# Bright Orange (Vibrant)
color17 #FE7C0D

# --- UI COLORS ---

url_color #458588

# Selection:
selection_background  #FE7C0D
selection_foreground  #282828

# Cursor: Cream Block with Dark Text
cursor                #F9EDD2
cursor_text_color     #282828

# --- TABS (Powerline Style) ---
tab_bar_style powerline

# Active Tab: Bright Orange BG, Dark Text
active_tab_background #FE7C0D
active_tab_foreground   #282828
active_tab_font_style   bold

# Inactive Tab: Normal Orange BG, Dark Text
inactive_tab_background #D75C0F
inactive_tab_foreground #282828
inactive_tab_font_style normal

text_composition_strategy platform
